name: test-javascript

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test-javascript:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        node-version: ['14.x', '16.11.x', '17.x', '18.x']

    steps:
      - name: set git core.autocrlf to 'input'
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v3
      - uses: mymindstorm/setup-emsdk@v11
        with:
          # See https://github.com/tree-sitter/tree-sitter/blob/master/cli/emscripten-version
          version: 2.0.24
      - name: with Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install-test
      - run: npm run eslint
